market rep update - time to go and fuckin die lmao
Sonnet-Discord/sonnet-modules pull request #1
Opened 2021-05-03 16:16 UTC by xFuney

Tested, should work. Still needs some commands and extra polishing (I'm scared of Python)

2021-05-03 17:39 UTC, ultrabear requested changes
a few minor issues /s
god help me

2021-05-03 17:39 UTC, ultrabear commented on mod/ultrabear/marketrep/cmd_marketrep.py
> +        etypes.append("Could not remove old rep role (404)")
this formatting is wrong and makes it bugged

2021-05-03 17:39 UTC, ultrabear commented on mod/ultrabear/marketrep/cmd_marketrep.py
> +            return 1
This blatantly will fatal error as it doesnt check for greps before assuming it exists
please use mypy and pyflakes, it would catch these errors

2021-05-03 17:39 UTC, ultrabear commented on mod/ultrabear/marketrep/cmd_marketrep.py
> +        "permission": "administrator",
These perms should be moderator, and setting the configs should remain admin

2021-05-03 17:39 UTC, ultrabear commented on mod/ultrabear/marketrep/cmd_marketrep.py
> +        "pretty_name": "mr-increp <mention/id>",
using `<mention/id>` when all other specs use `<user>`, ok ig

2021-05-03 17:39 UTC, ultrabear commented on mod/ultrabear/marketrep/cmd_marketrep.py
> -        rdb = json.loads(db.grab_config("mr-roles") or "{}")
I completely dont see the point of moving this and it functionally makes no difference
however it makes the separate tasks of grabbing the role db and incrementing the user not grouped up and decreases readability

2021-05-16 18:44 UTC, xFuney reviewed
Made changes as per CR, should be checked again though (I'm not the best at Python).

2021-05-16 18:44 UTC, xFuney commented on mod/ultrabear/marketrep/cmd_marketrep.py
> +            return 1
Should be resolved in latest push to development branch.

2021-05-16 18:44 UTC, xFuney commented on mod/ultrabear/marketrep/cmd_marketrep.py
> +        etypes.append("Could not remove old rep role (404)")
Should be fixed.

2021-05-16 18:44 UTC, xFuney commented on mod/ultrabear/marketrep/cmd_marketrep.py
> +        "permission": "administrator",
Fixed.

2021-05-16 18:44 UTC, xFuney commented on mod/ultrabear/marketrep/cmd_marketrep.py
> +        "pretty_name": "mr-increp <mention/id>",
Fixed - brought up to spec.

2021-05-16 18:48 UTC, ultrabear commented on mod/ultrabear/marketrep/cmd_marketrep.py
> +            rep_number: int = int(grep[1]-1)
this is still busted but i dont care ill just fix it on my end

2021-05-16 18:49 UTC, ultrabear approved these changes

2021-05-16 18:49 UTC, merged